In [25]:
import tensorflow as tf
import numpy as np

In [26]:
def generate_test_input(N):
    # Formato: (x1, y1, w1, h1, theta1)
    # Gerar boxes preditas e alvo aleatórias
    boxes_pred = np.random.rand(N, 5)*100  # N amostras de boxes preditas
   
    target_boxes = np.random.rand(N, 5)*100  # N amostras de boxes alvo

    # Adicionar valores específicos para o ângulo em radianos
    angle_values = np.random.uniform(low=0, high=2*np.pi, size=(N, 1))  # N valores de ângulo em radianos
    boxes_pred[:, 4] = angle_values.flatten()  # Substituição - Adicionando ângulos às boxes preditas
    target_boxes[:, 4] = angle_values.flatten()  # Substituição - Adicionando ângulos às boxes alvo
    
    return boxes_pred, target_boxes

In [183]:
def probiou_loss_og(boxes_pred, target_boxes_, EPS = 1e-3, mode='l2'):

    """
        boxes_pred    -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours predicted box ;in case of HBB angle == 0
        target_boxes_  -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours target    box ;in case of HBB angle == 0
        EPS     -> threshold to avoid infinite values
        mode       -> ('l1' in [0,1] or 'l2' in [0,inf]) metrics according our paper

    """

    x1, y1, w1, h1, theta1 = tf.unstack(boxes_pred, axis=1)
    x2, y2, w2, h2, theta2 = tf.unstack(target_boxes_, axis=1)
    x1 = tf.reshape(x1, [-1, 1])
    y1 = tf.reshape(y1, [-1, 1])
    h1 = tf.reshape(h1, [-1, 1])
    w1 = tf.reshape(w1, [-1, 1])
    theta1 = tf.reshape(theta1, [-1, 1])
    x2 = tf.reshape(x2, [-1, 1])
    y2 = tf.reshape(y2, [-1, 1])
    h2 = tf.reshape(h2, [-1, 1])
    w2 = tf.reshape(w2, [-1, 1])
    theta2 = tf.reshape(theta2, [-1, 1])

    # gbb form
    aa = w1**2/12; bb = h1**2/12; angles = theta1
    # rotated form
    a1 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b1 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c1 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

    # gbb form
    aa = w2**2/12; bb = h2**2/12; angles = theta2
    # rotated form
    a2 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b2 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c2 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

    # B1 ORIGINAL
    # B1 = 1/4.*( (a1+a2)*(y1-y2)**2. + (b1+b2)*(x1-x2)**2. ) + 1/2.*( (c1+c2)*(x2-x1)*(y1-y2) )
    # B1 = B1 / ( (a1+a2)*(b1+b2) - (c1+c2)**2. + EPS )
    
    a1=tf.Variable([1], dtype=tf.float64) # elementos matriz sigma1
    c1=tf.Variable([2], dtype=tf.float64) # 1 2
    b1=tf.Variable([6], dtype=tf.float64) # 2 6
    
    a2=tf.Variable([2], dtype=tf.float64) # elementos matriz sigma2
    c2=tf.Variable([3], dtype=tf.float64) # 2 3
    b2=tf.Variable([4], dtype=tf.float64) # 3 4
    
    x1=tf.Variable([4], dtype=tf.float64) # 4 elementos matriz mu1
    y1=tf.Variable([4], dtype=tf.float64) # 4
    
    x2=tf.Variable([2], dtype=tf.float64) # 2 elementos matriz mu2 
    y2=tf.Variable([2], dtype=tf.float64) # 2
    
    # B1 TESTE
    B1 = 2/8.*(np.array([(x1-x2)*(b1+b2)-(y1-y2)*(c1+c2), (x2-x1)*(c1+c2)+(a1+a2)*(y1-y2)]))
    B1 = B1 / ( (a1+a2)*(b1+b2) - (c1+c2)**2.)
    

    print("valor de b1 na loss OG:{}".format(B1))
    sqrt = (a1*b1-c1**2)*(a2*b2-c2**2)
    # sqrt = tf.clip_by_value(sqrt, EPS, tf.reduce_max(sqrt)+EPS)
    # sqrt = tf.clip_by_value(sqrt, EPS, tf.reduce_max(sqrt))
    # B2 = ( (a1+a2)*(b1+b2) - (c1+c2)**2. )/( 4.*tf.math.sqrt(sqrt) + EPS )
    B2 = ( (a1+a2)*(b1+b2) - (c1+c2)**2. )/( 4.*tf.math.sqrt(sqrt))
    #B2 = tf.clip_by_value(B2, EPS, tf.reduce_max(B2)+EPS)
    B2 = 1/2.*tf.math.log(B2)
    
    #print(B2.shape)

    #print("valor de b2 na LOSS OG{}".format(B2))
    
    Bd = B1 + B2
    Bd = tf.clip_by_value(Bd, EPS, 100.)
    
    #print(Bd.shape)

    l1 = tf.math.sqrt(1 - tf.math.exp(-Bd) + EPS)

    if mode=='l2':
        l2 = tf.math.pow(l1, 2.)
        probiou = - tf.math.log(1. - l2 + EPS)
    else:
        probiou = l1

    return B1

In [184]:
def probiou_loss_tf(boxes_pred, target_boxes_, EPS = 1e-3, mode='l2'):

    """
        boxes_pred    -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours predicted box ;in case of HBB angle == 0
        target_boxes_  -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours target    box ;in case of HBB angle == 0
        EPS     -> threshold to avoid infinite values
        mode       -> ('l1' in [0,1] or 'l2' in [0,inf]) metrics according our paper

    """

    x1, y1, w1, h1, theta1 = tf.unstack(boxes_pred, axis=1)
    x2, y2, w2, h2, theta2 = tf.unstack(target_boxes_, axis=1)
    x1 = (tf.reshape(x1, [-1])).numpy()
    y1 = (tf.reshape(y1, [-1])).numpy()
    h1 = (tf.reshape(h1, [-1])).numpy()
    w1 = (tf.reshape(w1, [-1])).numpy()
    theta1 = (tf.reshape(theta1, [-1])).numpy()
    x2 = (tf.reshape(x1, [-1])).numpy()
    y2 = (tf.reshape(y2, [-1])).numpy()
    h2 = (tf.reshape(h2, [-1])).numpy()
    w2 = (tf.reshape(w2, [-1])).numpy()
    theta2 = (tf.reshape(theta2, [-1])).numpy()

    # gbb form
    # print("O valor de w1 eh: {}".format(w1))
    # print("O valor de h1 eh: {}".format(h1))
    # print("O valor de theta1 eh: {}".format(theta1))
    aa = w1**2/12; bb = h1**2/12; angles = theta1
    # rotated form
    a1 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b1 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c1 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

    # gbb form
    aa = w2**2/12; bb = h2**2/12; angles = theta2
    # rotated form
    a2 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b2 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c2 = 0.5*(aa - bb)*tf.math.sin(2.*angles)
    
    # print(tf.rank(a1))
    # print("a1:{}".format(a1))
    # print("c1:{}".format(c1))
    # print("b1:{}".format(b1))
    
    a1=tf.Variable([1], dtype=tf.float64) # elementos matriz sigma1
    c1=tf.Variable([2], dtype=tf.float64) # 1 2
    b1=tf.Variable([6], dtype=tf.float64) # 2 6
    
    a2=tf.Variable([2], dtype=tf.float64) # elementos matriz sigma2
    c2=tf.Variable([3], dtype=tf.float64) # 2 3
    b2=tf.Variable([4], dtype=tf.float64) # 3 4
    
    x1=tf.Variable([4], dtype=tf.float64) # 4 elementos matriz mu1
    y1=tf.Variable([4], dtype=tf.float64) # 4
    
    x2=tf.Variable([2], dtype=tf.float64) # 2 elementos matriz mu2 
    y2=tf.Variable([2], dtype=tf.float64) # 2
    
    # Formulação matricial
    sigma1 = tf.transpose(tf.Variable([[a1, c1], [c1, b1]],), perm=[2, 1, 0]) # sigma1 tem dim (n, 2, 2)
    
    sigma2 = tf.transpose(tf.Variable([[a2, c2], [c2, b2]]), perm=[2, 1, 0])  # sigma2 tem dim (n, 2, 2)
    
    sigma = (1/2)*(sigma1 + sigma2)
    
    mu1 = tf.transpose(tf.expand_dims(tf.Variable([x1, y1]), axis=-1), perm=[1, 0, 2]) # mu1 tem dim (n, 2, 1)
    
    mu2 = tf.transpose(tf.expand_dims(tf.Variable([x2, y2]), axis=-1), perm=[1, 0, 2]) # mu2 tem dim (n, 2, 1)
    
    b1 = (1/8)*tf.linalg.matmul(tf.transpose((mu1 - mu2), perm=[0, 2, 1]), tf.linalg.inv(sigma))
    # b1 = tf.squeeze(tf.linalg.matmul(b1, (mu1 - mu2)), axis=2)
    
    # teste
    # b1 = tf.linalg.matmul(tf.linalg.inv(sigma), (mu1 - mu2))
    # b1 = (1/8)*tf.linalg.matmul(tf.transpose((mu1 - mu2), perm=[0, 2, 1]), b1)
    
    print("valor de b1 loss TF: ", b1)
    
    b2 = (1/2)*tf.math.log(tf.linalg.det(sigma)/tf.math.sqrt(tf.linalg.det(sigma1)*tf.linalg.det(sigma2)))
    #print("valor de pt2: ", b2)
    
    Bd = b1+b2
    
    Bd = tf.clip_by_value(Bd, EPS, 100.)

    l1 = tf.math.sqrt(1 - tf.math.exp(-Bd) + EPS)
    
    if mode=='l2':
        l2 = tf.math.pow(l1, 2.)
        probiou = - tf.math.log(1. - l2 + EPS)
    else:
        probiou = l1
        
    return b1


In [185]:
def probiou_loss(boxes_pred, target_boxes_, EPS = 1e-3, mode='l2'):

    """
        boxes_pred    -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours predicted box ;in case of HBB angle == 0
        target_boxes_  -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours target    box ;in case of HBB angle == 0
        EPS     -> threshold to avoid infinite values
        mode       -> ('l1' in [0,1] or 'l2' in [0,inf]) metrics according our paper

    """

    x1, y1, w1, h1, theta1 = tf.unstack(boxes_pred, axis=1)
    x2, y2, w2, h2, theta2 = tf.unstack(target_boxes_, axis=1)
    x1 = (tf.reshape(x1, [-1])).numpy()
    y1 = (tf.reshape(y1, [-1])).numpy()
    h1 = (tf.reshape(h1, [-1])).numpy()
    w1 = (tf.reshape(w1, [-1])).numpy()
    theta1 = (tf.reshape(theta1, [-1])).numpy()
    x2 = (tf.reshape(x1, [-1])).numpy()
    y2 = (tf.reshape(y2, [-1])).numpy()
    h2 = (tf.reshape(h2, [-1])).numpy()
    w2 = (tf.reshape(w2, [-1])).numpy()
    theta2 = (tf.reshape(theta2, [-1])).numpy()

    # gbb form
    # print("O valor de w1 eh: {}".format(w1))
    # print("O valor de h1 eh: {}".format(h1))
    # print("O valor de theta1 eh: {}".format(theta1))
    aa = w1**2/12; bb = h1**2/12; angles = theta1
    # rotated form
    a1 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b1 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c1 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

    # gbb form
    aa = w2**2/12; bb = h2**2/12; angles = theta2
    # rotated form
    a2 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b2 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c2 = 0.5*(aa - bb)*tf.math.sin(2.*angles)
    
    # print(tf.rank(a1))
    # print("a1:{}".format(a1))
    # print("c1:{}".format(c1))
    # print("b1:{}".format(b1))

    # Formulação matricial
    sigma1 = np.array([[a1, c1],
                  [c1, b1]]).T.reshape(boxes_pred.shape[0], 2, 2)

    sigma2 = np.array([[a2, c2],
                  [c2, b2]]).T.reshape(boxes_pred.shape[0], 2, 2)

    mu1 = np.array([[x1], [y1]]).T.reshape(boxes_pred.shape[0], 2, 1)

    mu2 = np.array([[x2], [y2]]).T.reshape(boxes_pred.shape[0], 2, 1)
    
    sigma = np.dot(sigma1 + sigma2, 1/2)

    b1 = np.dot(1/8, (mu1 - mu2).transpose(0, 2, 1) @ np.linalg.inv(sigma) @ (mu1-mu2))
    
    print("valor de b1 na loss Numpy: ", b1)
    
    #print(sigma.shape)
    digs = np.linalg.det(sigma)
    #print(digs)
    b2 = np.dot(1/2, np.log(np.linalg.det(sigma)*(1/np.sqrt(np.linalg.det(sigma1)*np.linalg.det(sigma2)))))
    
    #print("valor de b2 na minha LOSS{}".format(b2))
    
    Bd = b1+b2
    
    Bd = tf.clip_by_value(Bd, EPS, 100.)
    
    # print(Bd)

    l1 = tf.math.sqrt(1 - tf.math.exp(-Bd) + EPS)
    
    if mode=='l2':
        l2 = tf.math.pow(l1, 2.)
        probiou = - tf.math.log(1. - l2 + EPS)
    else:
        probiou = l1
        
    return probiou

In [186]:
boxes_predd, target_boxess = generate_test_input(1)

In [187]:
digs1 = probiou_loss(boxes_predd, target_boxess)

valor de b1 na loss Numpy:  [[[6.72745571]]]


In [188]:
digs6 = probiou_loss_tf(boxes_predd, target_boxess)

valor de b1 loss TF:  tf.Tensor([[[ 0.5 -0.2]]], shape=(1, 1, 2), dtype=float64)


In [189]:
digs7 = probiou_loss_og(boxes_predd, target_boxess)

valor de b1 na loss OG:[[ 0.5]
 [-0.2]]


# Análise de Tempo

In [108]:
%timeit \
digs3 = probiou_lossTF(boxes_predd, target_boxess)

5.15 ms ± 5.06 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [109]:
%timeit \
digs2 = probiou_loss_og(boxes_predd, target_boxess)

3.86 ms ± 6.36 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [110]:
%timeit \
digs1 = probiou_loss(boxes_predd, target_boxess)

2.93 ms ± 8.04 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Debug

In [258]:
a1=tf.Variable([1], dtype=tf.float64) # elementos matriz sigma1
c1=tf.Variable([2], dtype=tf.float64) # 1 2
b1=tf.Variable([6], dtype=tf.float64) # 2 6
    
a2=tf.Variable([2], dtype=tf.float64) # elementos matriz sigma2
c2=tf.Variable([3], dtype=tf.float64) # 2 3
b2=tf.Variable([4], dtype=tf.float64) # 3 4
    
x1=tf.Variable([4], dtype=tf.float64) # 4 elementos matriz mu1
y1=tf.Variable([4], dtype=tf.float64) # 4
    
x2=tf.Variable([2], dtype=tf.float64) # 2 elementos matriz mu2 
y2=tf.Variable([2], dtype=tf.float64) # 2

sigma1 = tf.transpose(tf.Variable([[a1, c1], [c1, b1]],), perm=[2, 1, 0]) # sigma1 tem dim (n, 2, 2)
    
sigma2 = tf.transpose(tf.Variable([[a2, c2], [c2, b2]]), perm=[2, 1, 0])  # sigma2 tem dim (n, 2, 2)

mu1 = tf.transpose(tf.expand_dims(tf.Variable([x1, y1]), axis=-1), perm=[1, 0, 2]) # mu1 tem dim (n, 2, 1)
    
mu2 = tf.transpose(tf.expand_dims(tf.Variable([x2, y2]), axis=-1), perm=[1, 0, 2]) # mu2 tem dim (n, 2, 1)
    
sigma = (1/2)*(sigma1 + sigma2)
    
sigmainv = tf.linalg.inv(sigma)
    
print(" valor de sigma: ", sigma)
    
print(" valor de sigmainv: ", sigmainv)

testedebug = (1/8)*tf.linalg.matmul(tf.transpose((mu1-mu2), perm=[0, 2, 1]), tf.linalg.inv(sigma))
    
testedebug2 = tf.linalg.matmul(testedebug, (mu1 - mu2))
    
print(" valor de testedebug2: ", testedebug2)

 valor de sigma:  tf.Tensor(
[[[1.5 2.5]
  [2.5 5. ]]], shape=(1, 2, 2), dtype=float64)
 valor de sigmainv:  tf.Tensor(
[[[ 4.  -2. ]
  [-2.   1.2]]], shape=(1, 2, 2), dtype=float64)
 valor de testedebug2:  tf.Tensor([[[0.6]]], shape=(1, 1, 1), dtype=float64)
