In [179]:
import tensorflow as tf
import numpy as np

In [180]:
def generate_test_input(N):
    # Gerar boxes preditas e alvo aleatórias
    boxes_pred = np.random.rand(N, 5)  # N amostras de boxes preditas
    target_boxes = np.random.rand(N, 5)  # N amostras de boxes alvo

    # Adicionar valores específicos para o ângulo em radianos
    angle_values = np.random.uniform(low=0, high=2*np.pi, size=(N, 1))  # N valores de ângulo em radianos
    boxes_pred[:, 4] = angle_values.flatten()  # Adicionar ângulos às boxes preditas
    target_boxes[:, 4] = angle_values.flatten()  # Adicionar ângulos às boxes alvo

    return boxes_pred, target_boxes

In [202]:
def probiou_loss_og(boxes_pred, target_boxes_, EPS = 1e-3, mode='l2'):

    """
        boxes_pred    -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours predicted box ;in case of HBB angle == 0
        target_boxes_  -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours target    box ;in case of HBB angle == 0
        EPS     -> threshold to avoid infinite values
        mode       -> ('l1' in [0,1] or 'l2' in [0,inf]) metrics according our paper

    """

    x1, y1, w1, h1, theta1 = tf.unstack(boxes_pred, axis=1)
    x2, y2, w2, h2, theta2 = tf.unstack(target_boxes_, axis=1)
    x1 = tf.reshape(x1, [-1, 1])
    y1 = tf.reshape(y1, [-1, 1])
    h1 = tf.reshape(h1, [-1, 1])
    w1 = tf.reshape(w1, [-1, 1])
    theta1 = tf.reshape(theta1, [-1, 1])
    x2 = tf.reshape(x2, [-1, 1])
    y2 = tf.reshape(y2, [-1, 1])
    h2 = tf.reshape(h2, [-1, 1])
    w2 = tf.reshape(w2, [-1, 1])
    theta2 = tf.reshape(theta2, [-1, 1])

    # gbb form
    aa = w1**2/12; bb = h1**2/12; angles = theta1
    # rotated form
    a1 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b1 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c1 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

    # gbb form
    aa = w2**2/12; bb = h2**2/12; angles = theta2
    # rotated form
    a2 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b2 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c2 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

    B1 = 1/4.*( (a1+a2)*(y1-y2)**2. + (b1+b2)*(x1-x2)**2. ) + 1/2.*( (c1+c2)*(x2-x1)*(y1-y2) )
    B1 = B1 / ( (a1+a2)*(b1+b2) - (c1+c2)**2. + EPS )


    sqrt = (a1*b1-c1**2)*(a2*b2-c2**2)
    sqrt = tf.clip_by_value(sqrt, EPS, tf.reduce_max(sqrt)+EPS)
    B2 = ( (a1+a2)*(b1+b2) - (c1+c2)**2. )/( 4.*tf.math.sqrt(sqrt) + EPS )
    B2 = tf.clip_by_value(B2, EPS, tf.reduce_max(B2)+EPS)
    B2 = 1/2.*tf.math.log(B2)

    Bd = B1 + B2
    Bd = tf.clip_by_value(Bd, EPS, 100.)

    l1 = tf.math.sqrt(1 - tf.math.exp(-Bd) + EPS)

    if mode=='l2':
        l2 = tf.math.pow(l1, 2.)
        probiou = - tf.math.log(1. - l2 + EPS)
    else:
        probiou = l1

    return probiou

In [203]:
def probiou_loss(boxes_pred, target_boxes_, EPS = 1e-3, mode='l2'):

    """
        boxes_pred    -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours predicted box ;in case of HBB angle == 0
        target_boxes_  -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours target    box ;in case of HBB angle == 0
        EPS     -> threshold to avoid infinite values
        mode       -> ('l1' in [0,1] or 'l2' in [0,inf]) metrics according our paper

    """

    x1, y1, w1, h1, theta1 = tf.unstack(boxes_pred, axis=1)
    x2, y2, w2, h2, theta2 = tf.unstack(target_boxes_, axis=1)
    x1 = tf.reshape(x1, [-1, 1])
    y1 = tf.reshape(y1, [-1, 1])
    h1 = tf.reshape(h1, [-1, 1])
    w1 = tf.reshape(w1, [-1, 1])
    theta1 = tf.reshape(theta1, [-1, 1])
    x2 = tf.reshape(x2, [-1, 1])
    y2 = tf.reshape(y2, [-1, 1])
    h2 = tf.reshape(h2, [-1, 1])
    w2 = tf.reshape(w2, [-1, 1])
    theta2 = tf.reshape(theta2, [-1, 1])

    # gbb form
    # print("O valor de w1 eh: {}".format(w1))
    # print("O valor de h1 eh: {}".format(h1))
    # print("O valor de theta1 eh: {}".format(theta1))
    aa = w1**2/12; bb = h1**2/12; angles = theta1
    # rotated form
    a1 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b1 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c1 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

    # gbb form
    aa = w2**2/12; bb = h2**2/12; angles = theta2
    # rotated form
    a2 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b2 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c2 = 0.5*(aa - bb)*tf.math.sin(2.*angles)
    
    # print(tf.rank(a1))
    # print(a1)

    # Formulação matricial
    sigma = tf.stack([[a1, c1],
                  [c1, b1]])

    sigma2 = tf.stack([[a2, c2],
                  [c2, b2]])

    mu1 = tf.stack([[x1], [y1]])

    mu2 = tf.stack([[x2], [y2]])
    
    mu = tf.multiply(tf.add(mu1, mu2), 0.5)
    
    # print(mu)
    
    bd = tf.add(tf.multiply(tf.multiply(tf.multiply(tf.transpose(tf.subtract(mu1, mu2)), tf.linalg.inv(mu)),tf.subtract(mu1, mu2)), 1/8),
                tf.multiply(tf.math.log(tf.linalg.det(mu)/(tf.sqrt(tf.linalg.det(mu1)*tf.linalg.det(mu2)))), 1/2)) #eq7
    
    bd = tf.clip_by_value(bd, EPS, 100.)
    
    print(bd)

    l1 = tf.math.sqrt(1 - tf.math.exp(-bd) + EPS)
    
    if mode=='l2':
        l2 = tf.math.pow(l1, 2.)
        probiou = - tf.math.log(1. - l2 + EPS)
    else:
        probiou = l1
        
    return probiou

In [204]:
boxes_predd, target_boxess = generate_test_input(1)

In [205]:
digs1 = probiou_loss(boxes_predd, target_boxess)
digs2 = probiou_loss_og(boxes_predd, target_boxess)

print(digs1)
print(digs2)

tf.Tensor(
[[[[0.04170192 0.02633809]
   [0.13790576 0.12254192]]]


 [[[0.06963806 0.03524166]
   [0.16584189 0.1314455 ]]]], shape=(2, 1, 2, 2), dtype=float64)
tf.Tensor(
[[[[0.04170192 0.02633809]
   [0.13790576 0.12254192]]]


 [[[0.06963806 0.03524166]
   [0.16584189 0.1314455 ]]]], shape=(2, 1, 2, 2), dtype=float64)
tf.Tensor([[0.001]], shape=(1, 1), dtype=float64)


In [206]:
digs2 = probiou_loss_og(boxes_predd, target_boxess)
print(digs2)

tf.Tensor([[0.001]], shape=(1, 1), dtype=float64)


In [207]:
w = 0.7301464
h1 = 0.5703776
theta1 = 4.0121395

aa = w**2/12; bb = h1**2/12; angles = theta1
    # rotated form
a1 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
b1 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
c1 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

# Criando a matriz sigma
sigma = tf.stack([[a1, c1],
                  [c1, b1]])