In [126]:
import tensorflow as tf
import numpy as np

In [127]:
tf.config.experimental_run_functions_eagerly(True)

In [152]:
def generate_test_input(N):
    # Formato: (x1, y1, w1, h1, theta1)
    # Gerar boxes preditas e alvo aleatórias
    boxes_pred = np.random.rand(N, 5)*100  # N amostras de boxes preditas
   
    target_boxes = np.random.rand(N, 5)*100  # N amostras de boxes alvo

    # Adicionar valores específicos para o ângulo em radianos
    angle_values = np.random.uniform(low=0, high=2*np.pi, size=(N, 1))  # N valores de ângulo em radianos
    boxes_pred[:, 4] = angle_values.flatten()  # Substituição - Adicionando ângulos às boxes preditas
    target_boxes[:, 4] = angle_values.flatten()  # Substituição - Adicionando ângulos às boxes alvo
    
    return boxes_pred, target_boxes

In [153]:
boxes_predd, target_boxess = generate_test_input(5)

[[82.59939549 80.38853678 42.84327879 97.87215626 43.08097017]
 [51.18077633 84.09135463 87.59727337 65.84160699 42.84570811]
 [93.96448471 32.47529163 10.70095741 72.92754893 68.673144  ]
 [95.45367221 80.00090011 54.16695764 97.16826176 59.42857043]
 [81.08238653  4.76123757 44.64477495 37.72185766 30.65161641]]
[[29.07330112 72.76002128 21.61756601  6.55319705  6.16590643]
 [82.69119199  7.84072922 63.3208983  97.11892491  1.40260282]
 [95.6458847  79.71808304 81.23428824 19.54773891  3.77016132]
 [ 6.28035812 17.54073337 42.84268598 40.27229039  1.6225306 ]
 [11.19154146 20.98025647 49.62659671 94.2168665   2.96654608]]


In [166]:
def probiou_loss_og(boxes_pred, target_boxes_, EPS = 1e-3, mode='l2'):

    """
        boxes_pred    -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours predicted box ;in case of HBB angle == 0
        target_boxes_  -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours target    box ;in case of HBB angle == 0
        EPS     -> threshold to avoid infinite values
        mode       -> ('l1' in [0,1] or 'l2' in [0,inf]) metrics according our paper

    """

    x1, y1, w1, h1, theta1 = tf.unstack(boxes_pred, axis=1)
    x2, y2, w2, h2, theta2 = tf.unstack(target_boxes_, axis=1)
    x1 = tf.reshape(x1, [-1, 1])
    y1 = tf.reshape(y1, [-1, 1])
    h1 = tf.reshape(h1, [-1, 1])
    w1 = tf.reshape(w1, [-1, 1])
    theta1 = tf.reshape(theta1, [-1, 1])
    x2 = tf.reshape(x2, [-1, 1])
    y2 = tf.reshape(y2, [-1, 1])
    h2 = tf.reshape(h2, [-1, 1])
    w2 = tf.reshape(w2, [-1, 1])
    theta2 = tf.reshape(theta2, [-1, 1])

    # gbb form
    aa = w1**2/12; bb = h1**2/12; angles = theta1
    # rotated form
    a1 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b1 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c1 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

    # gbb form
    aa = w2**2/12; bb = h2**2/12; angles = theta2
    # rotated form
    a2 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b2 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c2 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

    B1 = 1/4.*( (a1+a2)*(y1-y2)**2. + (b1+b2)*(x1-x2)**2. ) + 1/2.*( (c1+c2)*(x2-x1)*(y1-y2) )
    # B1 = B1 / ( (a1+a2)*(b1+b2) - (c1+c2)**2. + EPS )
    B1 = B1 / ( (a1+a2)*(b1+b2) - (c1+c2)**2.)

    #print("valor de b1 na loss OG:{}".format(B1))
    sqrt = (a1*b1-c1**2)*(a2*b2-c2**2)
    # sqrt = tf.clip_by_value(sqrt, EPS, tf.reduce_max(sqrt)+EPS)
    # sqrt = tf.clip_by_value(sqrt, EPS, tf.reduce_max(sqrt))
    # B2 = ( (a1+a2)*(b1+b2) - (c1+c2)**2. )/( 4.*tf.math.sqrt(sqrt) + EPS )
    B2 = ( (a1+a2)*(b1+b2) - (c1+c2)**2. )/( 4.*tf.math.sqrt(sqrt))
    #B2 = tf.clip_by_value(B2, EPS, tf.reduce_max(B2)+EPS)
    B2 = 1/2.*tf.math.log(B2)

    #print("valor de b2 na LOSS OG{}".format(B2))
    
    Bd = B1 + B2
    Bd = tf.clip_by_value(Bd, EPS, 100.)

    l1 = tf.math.sqrt(1 - tf.math.exp(-Bd) + EPS)

    if mode=='l2':
        l2 = tf.math.pow(l1, 2.)
        probiou = - tf.math.log(1. - l2 + EPS)
    else:
        probiou = l1

    return B1

In [170]:
def probiou_lossTF(boxes_pred, target_boxes_, EPS = 1e-3, mode='l2'):

    """
        boxes_pred    -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours predicted box ;in case of HBB angle == 0
        target_boxes_  -> a matrix [N,5](x,y,w,h,angle - in radians) containing ours target    box ;in case of HBB angle == 0
        EPS     -> threshold to avoid infinite values
        mode       -> ('l1' in [0,1] or 'l2' in [0,inf]) metrics according our paper

    """

    x1, y1, w1, h1, theta1 = tf.unstack(boxes_pred, axis=1)
    x2, y2, w2, h2, theta2 = tf.unstack(target_boxes_, axis=1)
    x1 = tf.reshape(x1, [-1])
    y1 = tf.reshape(y1, [-1])
    h1 = tf.reshape(h1, [-1])
    w1 = tf.reshape(w1, [-1])
    theta1 = tf.reshape(theta1, [-1])
    x2 = tf.reshape(x1, [-1])
    y2 = tf.reshape(y2, [-1])
    h2 = tf.reshape(h2, [-1])
    w2 = tf.reshape(w2, [-1])
    theta2 = tf.reshape(theta2, [-1])

    # gbb form
    # print("O valor de w1 eh: {}".format(w1))
    # print("O valor de h1 eh: {}".format(h1))
    # print("O valor de theta1 eh: {}".format(theta1))
    aa = w1**2/12; bb = h1**2/12; angles = theta1
    # rotated form
    a1 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b1 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c1 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

    # gbb form
    aa = w2**2/12; bb = h2**2/12; angles = theta2
    # rotated form
    a2 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
    b2 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
    c2 = 0.5*(aa - bb)*tf.math.sin(2.*angles)
    
    # print(tf.rank(a1))
    # print("a1:{}".format(a1))
    # print("c1:{}".format(c1))
    # print("b1:{}".format(b1))

    # Formulação matricial
    sigma1 = tf.transpose(tf.Variable([[a1, c1], [c1, b1]],), perm=[2, 1, 0]) # sigma1 tem dim (n, 2, 2)
    
    sigma2 = tf.transpose(tf.Variable([[a2, c2], [c2, b2]]), perm=[2, 1, 0])  # sigma2 tem dim (n, 2, 2)
    
    sigma = (1/2)*(sigma1 + sigma2)
    
    mu1 = tf.transpose(tf.expand_dims(tf.Variable([x1, y1]), axis=-1), perm=[1, 0, 2]) # mu1 tem dim (n, 2, 1)
    
    mu2 = tf.transpose(tf.expand_dims(tf.Variable([x2, y2]), axis=-1), perm=[1, 0, 2]) # mu2 tem dim (n, 2, 1)
    
    b1 = (1/8)*tf.linalg.matmul(tf.transpose((mu1-mu2), perm=[0, 2, 1]), tf.linalg.inv(sigma))
    b1 = tf.linalg.matmul(b1, (mu1 - mu2))

    #print(b1)
    
    b2 = (1/2)*tf.math.log(tf.linalg.det(sigma)/tf.math.sqrt(tf.linalg.det(sigma1)*tf.linalg.det(sigma2)))
    #print("valor de pt2: ", b2)
    
    Bd = b1+b2
    
    Bd = tf.clip_by_value(Bd, EPS, 100.)
    
   # print(Bd.shape)

    l1 = tf.math.sqrt(1 - tf.math.exp(-Bd) + EPS)
    
    if mode=='l2':
        l2 = tf.math.pow(l1, 2.)
        probiou = - tf.math.log(1. - l2 + EPS)
    else:
        probiou = l1
        
    return b1


In [171]:
digs3 = probiou_lossTF(boxes_predd, target_boxess)

valor de pt2:  tf.Tensor([1.11637123 0.06273555 1.02195202 0.18670469 0.18823737], shape=(5,), dtype=float64)


In [172]:
digs2 = probiou_loss_og(boxes_predd, target_boxess)

valor de b2 na LOSS OG[[1.11637123]
 [0.06273555]
 [1.02195202]
 [0.18670469]
 [0.18823737]]


In [ ]:
w = 0.7301464
h1 = 0.5703776
theta1 = 4.0121395

aa = w**2/12; bb = h1**2/12; angles = theta1
    # rotated form
a1 = aa*tf.math.pow(tf.math.cos(angles), 2.) + bb*tf.math.pow(tf.math.sin(angles), 2.)
b1 = aa*tf.math.pow(tf.math.sin(angles), 2.) + bb*tf.math.pow(tf.math.cos(angles), 2.)
c1 = 0.5*(aa - bb)*tf.math.sin(2.*angles)

# Criando a matriz sigma
sigma = tf.stack([[a1, c1],
                  [c1, b1]])